53_杨楫_第三次作业
Guigulive/Team-F pull request #39
Opened 2018-03-20 03:50 UTC by yyssjj33

@taxic

2018-03-21 05:49 UTC, zchcai reviewed
minor fix needs

2018-03-21 05:49 UTC, taxic commented on Lesson-3/assignment/yours.sol
> +=========================================================================================
L(O) = [O]
L(A) = [A, O]
L(B) = [B, O]
L(C) = [C, O]
L(K2) = [K2] + merge(L(C), L(A), [C, A])
     = [K2] + merge([C, O], [A, O], [C, A])
     = [K2, C] + merge([O], [A, O], [A])
     = [K2, C, A, O]
L(K1) = [K1] + merge(L(B), L(A), [B, A])
     = [K1] + merge([B, O], [A, O], [B, A])
     = [K1, B] + merge([O], [A, O], [A])
     = [K1, B, A, O]
     
L(Z) = [Z] + merge(L(K2), L(K1), [K2, K1])
    = [Z] + merge([K2, C, A, O], [K1, B, A, O], [K2, K1])
    = [Z, K2] + merge([C, A, O], [K1, B, A, O], [K1])
    = [Z, K2, C] + merge([A, O], [K1, B, A, O], [K1])
    = [Z, K2, C, K1] + merge([A, O], [B, A, O])
    = [Z, K2, C, K1, B] + merge([A, O], [A, O])
    = [Z, K2, C, K1, B, A, O]

2018-03-21 05:49 UTC, taxic commented on Lesson-3/assignment/yours.sol
> +modifier partialPaid(employeeId) {
using partialPay as modifier is interesting. try to add employeeNonExist as well

2018-03-21 16:55 UTC, yyssjj33 commented
@taxic made some review changes

2018-03-22 21:33 UTC, zchcai requested changes

2018-03-22 21:33 UTC, taxic commented on Lesson-3/assignment/yours.sol
> +        var employee = employees[oldAddress];
require new Address not zero

2018-03-22 21:40 UTC, yyssjj33 commented
@taxic 已修改！

2018-03-22 22:11 UTC, zchcai approved these changes

2018-03-22 22:11 UTC, merged