Update yours.sol
Guigulive/Team-F pull request #8
Opened 2018-03-13 15:24 UTC by shihy52x

2018-03-13 15:25 UTC, shihy52x commented
First try

2018-03-13 15:25 UTC, shihy52x commented
second try

2018-03-13 15:25 UTC, shihy52x commented
third try

2018-03-14 04:11 UTC, zchcai requested changes
Can anyone change frank's "salary" or "address"?

2018-03-16 03:51 UTC, closed without merging